package Parse;

action code {: static Symbol.Symbol sym(String s) {
	         return Symbol.Symbol.symbol(s);
	        }
	    :};

parser code  {: 
  Lexer lexer;

  public void syntax_error(java_cup.runtime.Symbol current) {
   report_error("Syntax error (" + current.sym + ")", current);
  }

  ErrorMsg.ErrorMsg errorMsg;

  public void report_error(String message, java_cup.runtime.Symbol info) {
      errorMsg.error(info.left, message);
  }

  public Grm(Lexer l, ErrorMsg.ErrorMsg err) {
    this();
    errorMsg=err;
    lexer=l;
  }
:};

scan with {: return lexer.nextToken(); :};

//String declares value of token     INT is a token
//terminal nodes have values
terminal String ID, STRING;
terminal Integer INT;
terminal COMMA, COLON, SEMICOLON, LPAREN, RPAREN, LBRACK, RBRACK, 
	LBRACE, RBRACE, DOT, PLUS, MINUS, TIMES, DIVIDE, EQ, NEQ, LT, LE, 
	GT, GE, AND, OR, ASSIGN, ARRAY, IF, THEN, ELSE, WHILE, FOR, TO,
	DO, LET, IN, END, OF, BREAK, NIL, FUNCTION, VAR, TYPE;

//Absyn nodes are attached to non-terminal nodes
non terminal Absyn.Exp          Exp;
non terminal Absyn.Var          Var;


start with Exp;
//List of rules starts here
//Grammar rules take out values from terminaIs and non-terminals 

Exp ::= error:e
	  {: RESULT = new Absyn.SeqExp(eleft, null); :} //{} contain Java instructions that activate once Parse rule clears
	| Var:v //retreiving value from expression 
	  {: RESULT = new Absyn.VarExp(vleft, v); :}
	;

Var ::=   ID:n //
	  {: RESULT = new Absyn.SimpleVar(nleft, sym(n)); :}
	;